import pyautogui as aut
aut.hotkey('win','r')                
aut.sleep(1)
aut.write('chrome')
aut.sleep(0.5)
aut.press('enter')
aut.write('Youtube.com')
aut.sleep(0.5)
aut.press('enter')
aut.moveTo(870,113)
aut.sleep(1.5)
aut.click()
aut.write('pica pau')
aut.press('enter')
aut.moveTo(656,536)
aut.sleep(4.5)
aut.click()
aut.sleep(4.5)
aut.moveTo(1375,853)